name: PHP Tests
on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP-${{ matrix.php-versions }}: Quality"
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
        experimental: [false]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: cs2pr, phpcs, phpstan

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Install composer dependencies
        run: composer i --no-dev

      - name: Run PHPCS
        continue-on-error: false
        run: phpcs -q --report=checkstyle ApnsPHP --standard=PSR12 | cs2pr

      - name: Run PHPStan
        run: phpstan analyse ApnsPHP -l 5
